"""
rules/checker.py — LLM-based rule violation detector.

Two checking modes compare how well LLMs detect violations with different
information quality:

  ontology mode
      Structured rule condition (exact threshold + operator) is combined with
      precise individual property values extracted from the working OWL graph.
      The LLM evaluates each (subject, object) pair against the exact rule.
      Source refs are extracted programmatically from the OWL graph — no LLM
      needed to cite them.

  document mode
      A deliberately vague plain-English description (generated by generator.py)
      is combined with synthesized document text.  The LLM reads the prose and
      identifies violations without knowing the exact threshold.
      The LLM is asked to quote the verbatim passage(s) that support each finding.

Public API:
    check_rules(rules, provider, working_owl, document_path, mode, rules_file) -> ViolationReport
"""

from __future__ import annotations

import hashlib
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field
from rdflib import BNode, Graph, URIRef
from rdflib.namespace import RDF

from ontograph.llm import LLMMessage, LLMProvider, LLMRequest
from ontograph.rules.schema import OrgRule, ViolationInstance, ViolationReport
from ontograph.utils.owl import _SCHEMA_TYPES, load_graph


# ---------------------------------------------------------------------------
# Internal LLM response schemas
# ---------------------------------------------------------------------------

class PairViolation(BaseModel):
    """Ontology-mode LLM assessment.  Source refs are added programmatically after."""
    subject_label: str
    object_label:  str | None = None
    violated:      bool
    confidence:    float = Field(ge=0.0, le=1.0)
    explanation:   str


class RuleCheckResponse(BaseModel):
    """Ontology-mode LLM response for one rule."""
    rule_id:  str
    results:  list[PairViolation]


class PairViolationWithSources(BaseModel):
    """
    Document-mode LLM assessment.

    The LLM is instructed to populate ``source_refs`` with verbatim quoted
    sentence(s) from the document that most directly support its determination.
    """
    subject_label: str
    object_label:  str | None = None
    violated:      bool
    confidence:    float = Field(ge=0.0, le=1.0)
    explanation:   str
    source_refs:   list[str] = Field(
        default_factory=list,
        description="1–2 verbatim sentences quoted from the document. Empty list if none found.",
    )


class RuleCheckResponseWithSources(BaseModel):
    """Document-mode LLM response for one rule."""
    rule_id:  str
    results:  list[PairViolationWithSources]


# ---------------------------------------------------------------------------
# OWL helpers
# ---------------------------------------------------------------------------

def _individuals_of_type(
    g: Graph,
    class_local: str,
    namespace: str,
) -> dict[str, dict[str, str]]:
    """
    Return {iri_str: {predicate_local: object_str}} for all ABox individuals
    whose rdf:type matches ``namespace + class_local``.

    Only non-blank-node individuals are included.  If multiple values exist for
    the same predicate local name, they are joined with ", ".

    Args:
        g:            rdflib Graph containing the working OWL data.
        class_local:  Local name of the OWL class, e.g. "Battery".
        namespace:    Primary namespace IRI, e.g. "http://example.org/cubesat-ontology#".

    Returns:
        Mapping from individual IRI string to its property dict.
    """
    target_type = URIRef(namespace + class_local)
    result: dict[str, dict[str, list[str]]] = {}

    for subj in g.subjects(RDF.type, target_type):
        if isinstance(subj, BNode):
            continue
        props: dict[str, list[str]] = defaultdict(list)
        for _s, p, o in g.triples((subj, None, None)):
            if isinstance(o, BNode):
                continue
            pred_local = str(p).rsplit("#", 1)[-1].rsplit("/", 1)[-1]
            props[pred_local].append(str(o))
        result[str(subj)] = props  # type: ignore[assignment]

    # Flatten multi-valued properties to a single string for prompt readability
    return {
        iri: {k: (v[0] if len(v) == 1 else ", ".join(v)) for k, v in props.items()}
        for iri, props in result.items()
    }


def _local_label(iri: str) -> str:
    """Return the local name part of an IRI (after # or last /)."""
    return iri.rsplit("#", 1)[-1].rsplit("/", 1)[-1]


def _format_individual_block(
    label: str,
    individuals: dict[str, dict[str, str]],
    unit_hint: str | None = None,
    highlight_attr: str | None = None,
) -> str:
    """
    Format a set of individuals into a readable text block for LLM prompts.

    Example output::

        SUBJECT (PowerSubsystem) individuals:
          EPS1
            identifier: EPS-1
        OBJECT (Battery) individuals:
          BatteryPack1
            operatingTempMinC: -10 (°C)
            voltageV: 7.4
    """
    if not individuals:
        return f"  (no {label} individuals found in OWL)\n"

    lines = [f"{label} individuals:"]
    for iri, props in sorted(individuals.items()):
        name = _local_label(iri)
        lines.append(f"  {name}")
        for pred, val in sorted(props.items()):
            if pred == "type":
                continue
            suffix = f" ({unit_hint})" if (unit_hint and pred == highlight_attr) else ""
            lines.append(f"    {pred}: {val}{suffix}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Ontology-mode check (one LLM call per rule)
# ---------------------------------------------------------------------------

def _check_ontology_rule(
    rule: OrgRule,
    g: Graph,
    provider: LLMProvider,
) -> list[ViolationInstance]:
    """Check one rule against OWL individual data via LLM."""
    ns = rule.namespace

    # Collect individuals
    subj_inds: dict[str, dict[str, str]] = (
        _individuals_of_type(g, rule.subject_type, ns)
        if rule.subject_type else {}
    )
    obj_inds: dict[str, dict[str, str]] = (
        _individuals_of_type(g, rule.object_type, ns)
        if rule.object_type else {}
    )

    # For single-entity rules (no object_type), treat subject individuals as the targets
    if not rule.object_type:
        obj_inds = {}

    if not subj_inds and not obj_inds:
        return []

    # ── Build prompt ─────────────────────────────────────────────────────────
    cond_entity = rule.object_type if rule.object_type else rule.subject_type or "entity"
    cond_text = (
        f"{rule.when.attribute} of the {cond_entity} "
        f"{rule.when.operator} {rule.when.value}"
        + (f" {rule.when.unit}" if rule.when.unit else "")
    )

    subj_label = f"SUBJECT ({rule.subject_type})" if rule.subject_type else "TARGET"
    obj_label  = f"OBJECT ({rule.object_type})"   if rule.object_type  else None

    subj_block = _format_individual_block(
        subj_label, subj_inds,
        unit_hint=rule.when.unit, highlight_attr=rule.when.attribute,
    )
    obj_block = (
        _format_individual_block(
            obj_label, obj_inds,
            unit_hint=rule.when.unit, highlight_attr=rule.when.attribute,
        )
        if obj_inds else ""
    )

    consequence_line = f"Consequence : {rule.consequence}\n" if rule.consequence else ""
    note_line        = f"Note        : {rule.note}\n"        if rule.note        else ""

    user_msg = (
        f"Rule ID     : {rule.id}\n"
        f"Condition   : {cond_text}\n"
        f"{consequence_line}"
        f"{note_line}"
        f"\n{subj_block}\n"
        + (f"\n{obj_block}\n" if obj_block else "")
        + (
            "\nFor every (subject, object) pair, determine whether the rule condition "
            "is violated.  Return rule_id and a result entry for each pair."
            if rule.object_type
            else "\nFor each individual listed, determine whether the rule condition "
            "is violated.  Use the individual's local name as subject_label.  "
            "Return rule_id and a result entry for each individual."
        )
    )

    request = LLMRequest(
        messages=[
            LLMMessage(
                role="system",
                content=(
                    "You are an ontology rule checker.  Given a structured rule condition "
                    "and precise individual data extracted from an OWL ontology, determine "
                    "for each listed pair (or individual) whether the rule condition is "
                    "satisfied (violated=true) or not.  Provide a confidence score and a "
                    "brief explanation for each result."
                ),
            ),
            LLMMessage(role="user", content=user_msg),
        ],
        response_model=RuleCheckResponse,
    )
    response = provider.complete(request)
    check: RuleCheckResponse = response.parsed

    # ── Build reverse label → props lookup for programmatic source extraction ──
    obj_by_label  = {_local_label(iri): props for iri, props in obj_inds.items()}
    subj_by_label = {_local_label(iri): props for iri, props in subj_inds.items()}

    instances: list[ViolationInstance] = []
    for pv in check.results:
        # Determine which individual holds the checked attribute
        if rule.object_type and pv.object_label:
            props    = obj_by_label.get(pv.object_label, {})
            ref_name = pv.object_label
        else:
            props    = subj_by_label.get(pv.subject_label, {})
            ref_name = pv.subject_label

        attr_val = props.get(rule.when.attribute)
        unit_str = f" {rule.when.unit}" if rule.when.unit else ""
        source_refs = (
            [f"{ref_name} · {rule.when.attribute} = {attr_val}{unit_str}"]
            if attr_val is not None else []
        )

        instances.append(ViolationInstance(
            rule_id=rule.id,
            severity=rule.severity,
            mode="ontology",
            subject_label=pv.subject_label,
            object_label=pv.object_label,
            violated=pv.violated,
            confidence=pv.confidence,
            explanation=pv.explanation,
            source_refs=source_refs,
        ))
    return instances


# ---------------------------------------------------------------------------
# Document-mode check (one LLM call per rule)
# ---------------------------------------------------------------------------

def _check_document_rule(
    rule: OrgRule,
    document_text: str,
    provider: LLMProvider,
) -> list[ViolationInstance]:
    """Check one rule against synthesized document text via LLM."""
    plain = rule.plain_english.strip()
    if not plain:
        raise ValueError(
            f"Rule '{rule.id}' has no plain_english text. "
            "Run generate_all_plain_english() before checking in document mode."
        )

    user_msg = (
        f"Rule (plain English): {plain}\n\n"
        f"Document text:\n{document_text}\n\n"
        "Identify any components or component pairs mentioned in the document that "
        "appear to violate this rule.  Report the subject (and object if applicable) "
        "names as they appear in the document.  If no violations are found, return an "
        "empty results list.  Return rule_id and a result entry for each evaluated pair.\n\n"
        "For each result, populate source_refs with 1–2 sentences quoted VERBATIM from "
        "the document that directly support your determination.  If no directly relevant "
        "text exists, leave source_refs as an empty list.\n\n"
        f"Rule ID for all results: {rule.id}"
    )

    request = LLMRequest(
        messages=[
            LLMMessage(
                role="system",
                content=(
                    "You are a document-based rule checker.  Given a vague compatibility "
                    "guideline and engineering document text, identify any components or "
                    "component combinations that appear to violate the guideline based on "
                    "information described in the document.  Use the names as written in "
                    "the document.  Provide a confidence score and brief explanation for "
                    "each result found.  In source_refs, include 1–2 sentences quoted "
                    "verbatim from the document that most directly support your determination."
                ),
            ),
            LLMMessage(role="user", content=user_msg),
        ],
        response_model=RuleCheckResponseWithSources,
    )
    response = provider.complete(request)
    check: RuleCheckResponseWithSources = response.parsed

    return [
        ViolationInstance(
            rule_id=rule.id,
            severity=rule.severity,
            mode="document",
            subject_label=pv.subject_label,
            object_label=pv.object_label,
            violated=pv.violated,
            confidence=pv.confidence,
            explanation=pv.explanation,
            source_refs=pv.source_refs,
        )
        for pv in check.results
    ]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def check_rules(
    rules:         list[OrgRule],
    provider:      LLMProvider,
    working_owl:   Path | None = None,
    document_path: Path | None = None,
    mode:          Literal["ontology", "document", "both"] = "ontology",
    rules_file:    str = "",
) -> ViolationReport:
    """
    Run all rules through the LLM and return a ViolationReport.

    Args:
        rules:         List of OrgRule objects (from load_rules).
        provider:      LLM provider instance.
        working_owl:   Path to the working OWL file (required for ontology/both mode).
        document_path: Path to the synthesized document text (required for document/both mode).
        mode:          Which checking mode(s) to run.
        rules_file:    Path to the rules YAML file (stored in the report for traceability).

    Returns:
        A :class:`~ontograph.rules.schema.ViolationReport` with all results.

    Raises:
        ValueError: If required paths are missing for the selected mode.
    """
    # ── Validate required inputs ──────────────────────────────────────────────
    needs_owl = mode in ("ontology", "both")
    needs_doc = mode in ("document", "both")

    if needs_owl and working_owl is None:
        raise ValueError(f"mode='{mode}' requires working_owl path")
    if needs_doc and document_path is None:
        raise ValueError(f"mode='{mode}' requires document_path")

    # ── Load OWL graph ────────────────────────────────────────────────────────
    g: Graph | None = None
    if needs_owl and working_owl is not None:
        g = load_graph(working_owl, fmt="xml")

    # ── Load document text ────────────────────────────────────────────────────
    doc_text: str | None = None
    if needs_doc and document_path is not None:
        doc_text = Path(document_path).read_text(encoding="utf-8")

    # ── Run checks ────────────────────────────────────────────────────────────
    all_instances: list[ViolationInstance] = []

    for rule in rules:
        if needs_owl and g is not None:
            instances = _check_ontology_rule(rule, g, provider)
            all_instances.extend(instances)

        if needs_doc and doc_text is not None:
            instances = _check_document_rule(rule, doc_text, provider)
            all_instances.extend(instances)

    # ── Build report ──────────────────────────────────────────────────────────
    report_id = hashlib.sha256(
        f"{working_owl}|{document_path}|{mode}|{datetime.now(timezone.utc).isoformat()}".encode()
    ).hexdigest()[:16]

    return ViolationReport(
        id=report_id,
        created_at=datetime.now(timezone.utc).isoformat(),
        rules_file=rules_file or (str(rules[0].namespace) if rules else ""),
        owl_path=str(working_owl) if working_owl else None,
        document_path=str(document_path) if document_path else None,
        mode=mode,
        violations=all_instances,
    )
